### ISSUE TITLE
Theme change is not working after Restart App

### ISSUE THREAD

**Issue by kovacbb** [xamantra/listify#1]
Hi, great app, thanks for it.
I found one small bug.
After input clear (App restart) in Settings, theme can not be changed anymore.
Cheers!

**Comment by xamantra** [comment]
I will check this later...

**Comment by xamantra** [comment]
Fixed in commit [956e5edf57970556b4e937f40cf0f685c13ff457](https://github.com/xamantra/listify/commit/956e5edf57970556b4e937f40cf0f685c13ff457)

**Comment by kovacbb** [comment]
thanks, will this affect performance?

**Comment by xamantra** [comment]
@kovacbb, not exactly. With this update, restarting is now equivalent to calling `runApp(...)`.
